### ISSUE TITLE
Hey Chad I was playing with your implementation but when I try this simple setup .

### ISSUE THREAD

**Issue by jonntd** [chadmv/cmt#6]
import maya.cmds as cmds
j = cmds.joint()
sph, _ = cmds.polySphere()
print sph
cmds.skinCluster( j, sph)
cmds.select(sph)
cmds.demBones(b=20, sf=0, ef=20, eb=j)

# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
#   File "<string>", line 2, in demBones
# RuntimeError: Maya command error #

**Comment by asdMild** [comment]
i was also get this error, 
Are you solver it ?

**Comment by wujackjack** [comment]
parameter eb should be a list, it would work
