### ISSUE TITLE
maya 2018

### ISSUE THREAD

**Issue by asdMild** [chadmv/cmt#7]
thanks a lot about this project,
i try it in maya 2018.6,
there is some error about pyside2:
from PySide2.QtCore import QStringListModel

and there some plug-in error when run unit test runner :
RuntimeError: Plug-in, "cmt", was not found on MAYA_PLUG_IN_PATH.

i just want try skinning-converter which show in  your youtube video
is the maya 2020 required?

error logs:
======================================================================
ERROR: test_create (test_cmt_rbf.RBFTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\github\OpenLight\Maya\Enviroment\modules\cmt\tests\test_cmt_rbf.py", line 12, in test_create
    outputs=["{}.s{}".format(loc1, x) for x in "xyz"],
  File "D:\github\OpenLight\Maya\Enviroment\modules\cmt\scripts\cmt\rig\rbf.py", line 21, in create
    cmds.loadPlugin("cmt", qt=True)
RuntimeError: Plug-in, "cmt", was not found on MAYA_PLUG_IN_PATH.

======================================================================
ERROR: test_create_plot_demo (test_cmt_rbf.RBFTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\github\OpenLight\Maya\Enviroment\modules\cmt\tests\test_cmt_rbf.py", line 35, in test_create_plot_demo
    add_neutral_sample=False,
  File "D:\github\OpenLight\Maya\Enviroment\modules\cmt\scripts\cmt\rig\rbf.py", line 21, in create
    cmds.loadPlugin("cmt", qt=True)
RuntimeError: Plug-in, "cmt", was not found on MAYA_PLUG_IN_PATH.

**Comment by asdMild** [comment]
The release is perfect in maya 2020, other version is need build your self
